apiVersion: telemetry.kyma-project.io/v1alpha1
kind: MetricPipeline
metadata:
  name: sap-cloud-logging
spec:
  input:
    runtime:
      enabled: false
    promethues:
      enabled: true
  output:
    otlp:
      endpoint:
        value: http://localhost:4713
